branch-defaults:
  default:
    environment: Roker-env
environment-defaults:
  Relay-env-1:
    branch: null
    repository: null
global:
  application_name: relay
  default_ec2_keyname: sshkeypair
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
